name: what did I do last week?

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1'

jobs:
  work-report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install did
        run: |
          sudo apt install python3-pip libkrb5-dev --no-install-recommends
          pip3 install did
          mkdir -p /home/runner/.did
          cat ./did.config > /home/runner/.did/config
      - name: Run did
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "token = $GITHUB_TOKEN" >> /home/runner/.did/config
          did last week
          # Fail to get a notification every time
          exit 1
